name: CI (github to dockerhub image) to Deploy Helm

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mtmazurik/ng10e2e-ui:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  deploy:
    runs-on: self-hosted
    needs: [docker]
    steps:
      -
        name: Upgrade using Helm Chart
        run: helm install -release my-release cca-charts/ng10e2e-ui
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG}}
