on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: registrycca.azurecr.io
        username: ${{ secrets.acr_registrycca_username }}
        password: ${{ secrets.acr_registrycca_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t registrycca.azurecr.io/akstemporary:${{ github.sha }}
        docker push registrycca.azurecr.io/akstemporary:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akstemporary_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-temporarya8ca | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-temporarya8ca`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-temporarya8ca
        container-registry-url: registrycca.azurecr.io
        container-registry-username: ${{ secrets.acr_registrycca_username }}
        container-registry-password: ${{ secrets.acr_registrycca_password }}
        secret-name: akstemporarydockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-temporarya8ca
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          registrycca.azurecr.io/akstemporary:${{ github.sha }}
        imagepullsecrets: |
          akstemporarydockerauth